config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  root :to => 'submissions#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :problems, only: [:index]
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all.order(created_at: :desc)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      @submission.tag = 'master' if @submission.tag.empty?
      @submission.status = 'QUEUEING'
      if @submission.save
        ## for production
        SubmissionJob.perform_later(@submission)
        ## for debug
        #SubmissionRunner.new.run @submission

        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:problem, :repos_url, :tag)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
    def repos_link url, tag
        transd = url.sub(/\.git$/, '') + '/tree/' + tag
        link_to url, transd
    end

    def format_problem id
        p = Problem.find id
        "#{p.id}:#{p.name}"
    end
end

app/views/submissions/_form.html.erb
<%= form_for @submission, :html => { :class => "form-horizontal submission" } do |f| %>

  <% if @submission.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @submission.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :problem, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :problem, Problem.all, :id, :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:problem) %>
  </div>
  <div class="form-group">
    <%= f.label :repos_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :repos_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:repos_url) %>
  </div>
  <div class="form-group">
    <%= f.label :tag, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tag, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tag) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                submissions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/submissions/edit.html.erb
<%- model_class = Submission -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/submissions/index.html.erb
<%- model_class = Submission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_submission_path,
              :class => 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:problem) %></th>
      <th><%= model_class.human_attribute_name(:score) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= link_to submission.id, submission_path(submission) %></td>
        <td><%= link_to Problem.find(submission.problem).name, '/problems' %></td>
        <td><%= link_to (submission.score == nil) ? "-" : submission.score , submission_path(submission) %></td>
        <td><%= link_to submission.status, submission_path(submission) %></td>
        <td><%= submission.updated_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      submission_path(submission),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<%- model_class = Submission -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/submissions/show.html.erb
<%- model_class = Submission -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:id) %>:</strong></dt>
  <dd><%= @submission.id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:problem) %>:</strong></dt>
  <dd><%= link_to Problem.find(@submission.problem).name, '/problems' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:repos_url) %>:</strong></dt>
  <dd><%= repos_link @submission.repos_url, @submission.tag %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag) %>:</strong></dt>
  <dd><%= @submission.tag %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @submission.status %></dd>
  <% if @submission.status == 'COMPLETED' %>
  <dt><strong>Details :</strong></dt>
  <dd><%= link_to "Report ID: #{@submission.id}", "https://s3-ap-northeast-1.amazonaws.com/sabacon/results/#{@submission.id}/index.html" %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              submissions_path, :class => 'btn btn-default'  %>
